/*
 * For more details on building Java & JVM projects, please refer to https://docs.gradle.org/8.9/userguide/building_java_projects.html in the Gradle documentation.
 */

plugins {
    // Apply the java-library plugin for API and implementation separation.
    id("java-library")
    // publishing the built artifacts for local development
    id("maven-publish")

    // eclipse IDE plugin with annotation processing
    id("com.diffplug.eclipse.apt").version("3.44.0")
    // eclipse IDE plugin for integrating Ghidra with the Eclipse
    id("io.github.aquesnel.ghidra_gradle_build_scripts.GhidraEclipse").version("0.0.1")

    // code formatter plugin
    id("com.diffplug.spotless").version("6.25.0")
    // Gradle task dependency graph visualizer
    //id("com.dorongold.task-tree").version("4.0.0")
}

// apply the Ghidra build extention plugin
apply from: ext.getGhidraBuildExtentionPath()

repositories {
    // prioritize the local maven repo for local development dependencies
    mavenLocal()
    // Use Maven Central for resolving dependencies.
    mavenCentral()
}

dependencies {
    annotationProcessor("io.soabase.record-builder:record-builder-processor:41")
    compileOnly("io.soabase.record-builder:record-builder-core:41")
    
    implementation("com.google.guava:guava:31.1-jre")
        
    testImplementation("org.hamcrest:hamcrest:2.2")
    testImplementation("org.junit.jupiter:junit-jupiter:5.9.1")
}

// Apply a specific Java toolchain to ease working on different environments.
java {
    toolchain {
        languageVersion.set(JavaLanguageVersion.of(17))
    }
    withJavadocJar()
    withSourcesJar()
}


tasks.named("test") {
    useJUnitPlatform()
}

/*
TODO: once code is ready for spotless then enable this
spotless {
      java {
        googleJavaFormat()
      }
}
*/
publishing {
    publications {
        mavenJava(MavenPublication) {
            groupId = 'io.github.aquesnel'
            version = "0.0.1"
            from components.java
        }
    }
}
tasks.publish.dependsOn(check)
tasks.publishToMavenLocal.dependsOn(check)
tasks.build.dependsOn(publishToMavenLocal)

eclipse {
    project {
        natures("org.eclipse.jdt.core.javanature")
        buildCommand("org.eclipse.jdt.core.javabuilder")
    }
    classpath {
        file.whenMerged { cp ->
            
            // Add annotation processing generated source directories to the class path
//            cp.entries.add( new org.gradle.plugins.ide.eclipse.model.SourceFolder("build/generated/sources/annotationProcessor/java/main", null) )
            cp.entries.add( new org.gradle.plugins.ide.eclipse.model.SourceFolder(".apt_generated", null) )
        }
    }
}
tasks.eclipse.dependsOn(cleanEclipse)

